KEYCLOAK-11874 User should be evicted from cache when their credential is deleted
cloudtrust/keycloak pull request #29
Opened 2019-11-04 19:31 UTC by tkyjovsk

- added eviction of user after their credential was deleted
- added `UserTest.loginShouldFailAfterPasswordDeleted()`

2019-11-05 11:20 UTC, AlistairDoswald commented
@tkyjovsk Following this error, I went though the code to look for other locations where this could be a problem. I think we should also evict the cache in PasswordCredentialProvider.deleteCredential(RealmModel realm, UserModel user, String credentialId) (even though currently it's never called). Could you also do it it this PR? If not I'll just validate this PR, and do a follow-up one.

2019-11-05 12:46 UTC, tkyjovsk commented
Thinking about it, perhaps the eviction should be done after any credential deletion of any type, not just the passwords. In that case perhaps the `UserCredentialStoreManager.removeStoredCredential()` would be a better place to put it? That method is being called from all `*CredentialProvider.deleteCredential()` methods as well as the `UserResource.removeCredential()` method.

2019-11-05 13:01 UTC, AlistairDoswald commented
@tkyjovsk yes, it would be better I think. Safer at the very least.

2019-11-05 13:13 UTC, tkyjovsk commented
So I moved the eviction call from `UserResource` to the `UserCredentialStoreManager.removeStoredCredential()`. The test case is passing.

2019-11-05 13:20 UTC, mposolda approved these changes
@tkyjovsk @AlistairDoswald Agree about UserCredentialStoreManager being safer option. Approving.

2019-11-05 14:27 UTC, AlistairDoswald requested changes
Small clean-up problem introduced by this test. I'll be able to merge after it is corrected.

2019-11-05 14:27 UTC, AlistairDoswald commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        String userName = "credential-tester";
User `credential-tester` isn't getting cleaned up correctly after this test, and is causing tests count() and countUsersNotServiceAccount() to fail.

2019-11-06 10:17 UTC, tkyjovsk commented on testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/UserTest.java
> +        String userName = "credential-tester";
Right, sorry for missing that. It should be fixed in the next push.

2019-11-06 14:19 UTC, AlistairDoswald approved these changes

2019-11-06 14:19 UTC, merged